[package]
name = "protobuf-test"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
prost-reflect = "0.14.2"
prost-types = "0.13.3"
protobuf-parse = "3.6.0"
serde = "1.0.210"
serde_json = "1.0.128"
