[package]
name = "tantivy-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = "0.20.1"
tantivy = "0.22.0"
tempfile = "3.10.1"
