[package]
name = "iouring"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
io-uring = "0.7.2"
libc = "0.2.167"
tokio = { version = "1.42.0", features = ["full"] }
tokio-uring = "0.5.0"
