[package]
name = "rust_v8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.31.0"
serde = "1.0.202"
serde_json = "1.0.117"
v8 = "0.92.0"
