[package]
name = "dan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dan"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "53.1.0", features = ["pyarrow"] }
pyo3 = "0.22.0"
