import pyarrow.lib as palib
from typing import Union

def sum_as_string(a: int, b: int) -> str: ...

def double_arr(arr: Union[palib.Array, palib.ChunkedArray]) -> Union[palib.Array, palib.ChunkedArray]: ...
