[package]
name = "rafting"
version = "0.1.0"
edition = "2021"

[dependencies]
openraft = "0.9.17"
serde = { version = "1.0.213", features = ["serde_derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
